### ISSUE TITLE
Faucet needs to be restarted sometimes to find utxo

### ISSUE THREAD

**Issue by hewison-chris** [bosagora/faucet#145]
If the Faucet has no utxo to send and the last block was empty then it will remain waiting for utxo. After a restart it does find utxo and can recover. It should not need to be restarted to keep up to date with utxo.

**Comment by hewison-chris** [comment]
Still needs some more work.

**Comment by Geod24** [comment]
Maybe Faucet should just have a Ledger ?

**Comment by hewison-chris** [comment]
> Maybe Faucet should just have a Ledger ?

Yes I think that will be the way to go. However in the mean time we have https://github.com/bosagora/faucet/pull/149 which has been running in PROD since last week and doesn't require restarting. Perhaps we merge that first and open an issue to add ledger to Faucet.
