### ISSUE TITLE
Some portion of Transactions should include fees and data

### ISSUE THREAD

**Issue by omerfirmak** [bosagora/faucet#26]
To test the fee distribution on the live env, we need some of the generated transactions to include fees and/or data payload.

**Comment by ferencdg** [comment]
after this is done, minimum fee bug can be fixed: https://github.com/bosagora/agora/issues/2099

**Comment by Geod24** [comment]
The Agora side is ready, what's the ETA on this ?

**Comment by kchulj** [comment]
> The Agora side is ready, what's the ETA on this ?

ETA is tomorrow as of right now.

**Comment by Geod24** [comment]
Is this done ?

**Comment by kchulj** [comment]
> Is this done ?

This issue should have been solved by #128 .
@hewison-chris What do you think?

**Comment by hewison-chris** [comment]
We didn't add data but the fees are now included by the TxBuilder using default fee rate.
